id: 83b4ef64-9af6-4bec-9707-674fa82c2837
# Sets the URL name of the quickstart on public I/O (required)
slug: etcd

# Displayed in the UI (required)
title: Etcd

# Long-form description of the quickstart (required)
description: |
 ## What is Etcd?

 Etcd is a strongly consistent, distributed key-value store that provides a reliable way to store data that needs to be accessed by a distributed system or cluster of machines. It gracefully handles leader elections during network partitions and can tolerate machine failure, even in the leader node

 ## Quickstart details

 This quickstart was built based on `etcd` metrics sent to New Relic using Prometheus remote write.  If using with the Prometheus OpenMetrics Integration, the dashboard widgets will require some modification.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  A curated dashboard based on Prometheus metrics which helps you understand the health of your Etcd cluster.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Brad Schmitt

# Keywords for filtering / searching criteria in the UI
keywords:
  - etcd
  - kubernetes
  - k8s
  - prometheus
  - remote-write

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - setup-prometheus
#alerts:
dashboards:
  - etcd
# Documentation references
documentation:
  - name: Prometheus Remote Write Configuration
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/
    description: Configure your Prometheus Server to remote write metrics to New Relic
  - name: Etcd Metrics Documentation
    url: https://etcd.io/docs/v3.5/metrics/
    description: Learn more about the Prometheus metrics available for Etcd

# Content / Design
icon: logo.png
website: https://etcd.io/
