id: 5c1e7b31-df21-4acb-b72c-0a8786b88301
slug: aws-elasticache
description: |-
  What is Amazon ElastiCache?
  
  Deploy, operate, and scale an in-memory data store or cache in the cloud.
  
  ### Get started!
  
  Start monitoring Amazon ElastiCache by connecting Amazon Web Services (AWS) to New Relic!
  
  Check out our Amazon ElastiCache documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.
  
  ### More info
  
  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elasticache-monitoring-integration/) to learn more about New Relic monitoring for Amazon ElastiCache. "
summary: |-
  Monitor Amazon ElastiCache by connecting AWS to New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: Amazon ElastiCache
documentation:
  - name: Amazon ElastiCache installation docs
    description: Monitor Amazon ElastiCache by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elasticache-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - database
dashboards:
  - amazon-elasticache-memcached
installPlans:
  - aws-cloudwatch-metric-streams
