id: 980ab07a-3483-4b44-bbac-ed9c0a9a41a1
# Sets the URL name of the quickstart on public I/O (required)
slug: jenkins

# Displayed in the UI (required)
title: Jenkins

# Long-form description of the quickstart (required)
description: |-
  ## What is Jenkins?

  The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.

  ### Get started!

  Start monitoring Jenkins jobs and pipeline executions in New Relic!

  Check out our Monitoring Jenkins with OpenTelemetry and New Relic documentation to instrument your Jenkins instance with the OpenTelemetry plugin for Jenkins.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot/) to learn more about New Relic monitoring for Jenkins.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Monitor Jenkins with the OpenTelemetry plugin in New Relic.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - New Relic
  - Peter Nguyen

# Keywords for filtering / searching criteria in the UI
keywords:
  - jenkins
  - opentelemetry
  - otel
  - pipelines

dashboards:
  - jenkins

# Documentation references
documentation:
  - name: Set up Jenkins OpenTelemetry Plugin
    url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot/
    description: Monitor Jenkins with the OpenTelemetry plugin by visualizing jobs and pipeline executions as distributed traces.

# Content / Design
icon: logo.svg
website: https://www.newrelic.com
