id: d84051ba-365f-4542-8db9-0829384ea55a
slug: aws-emr
description: |-
  ## What is AWS EMR?
  
  Process and manage big data inputs from popular frameworks.
  
  ### Get started!
  
  Start monitoring AWS EMR by connecting Amazon Web Services (AWS) to New Relic!
  
  Check out our AWS EMR documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.
  
  ### More info
  
  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-emr-monitoring-integration/) to learn more about New Relic monitoring for AWS EMR.
summary: Monitor AWS EMR by connecting AWS to New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: AWS EMR
documentation:
  - name: AWS EMR installation docs
    description: Monitor AWS EMR by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-emr-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - big data 
  - analytics
installPlans:
  - aws-cloudwatch-metric-streams
